### ISSUE TITLE
Criar o modelo do banco de dados

### ISSUE THREAD

**Issue by Judison1** [Judison1/life-goals#2]
[Modelo DB](https://dbdiagram.io/d/5f6bf13a7da1ea736e2f1666)

**Comment by Judison1** [comment]
## Modificações para o modelo

1. Tabela 'tags' é uma tabela polimórfica many-to-many, verifica na [Documentação](https://laravel.com/docs/8.x/eloquent-relationships#one-to-many-polymorphic-relations);
2. Tabela 'attachments' também é uma tabela polimórfic one-to-many, [Documentação](https://laravel.com/docs/8.x/eloquent-relationships#one-to-many-polymorphic-relations)

**Comment by isaialcantara** [comment]
1. A tabela `tags` agora é uma tabela sem relações, removendo a relação _many-to-one_ com a tabela `boards`.
2. Foi criada a tabela `taggables` para a relação polimórfica _many-to-many_ entre `tags` e outras tabelas, substituindo a relação _many-to-many_ com a tabela `cards`.
3. A tabela `attachments` agora contém uma relação polimórfica via um `attachable`, substituindo a relação _many-to-one_ entre `attachments` e `cards`.
